### ISSUE TITLE
createClickwrap returns 404 Not Found

### ISSUE THREAD

**Issue by AndrejGajdos** [docusign/docusign-esign-node-client#298]
When I call `createClickwrap` method in my project, I got an error `404 Not Found`. I tried to debug Quickstart demo project and I don't get the error there. I don't know why I am getting this error in my project because `createClickwrap` function gets the same parametes in the demo app and in my project.

docusign controller:

```
const docuSignService = require('./docusign_esign_service');
const demoDocumentsPath = path.resolve(__dirname, '../demo_documents');
const { createClickwrap } = require('./createClickWrap');

async getDocusignRecieptService() {
    const authResponse = await docuSignService.authenticate();
    if (authResponse) {
      const docTermsPdf = 'Term_Of_Service.pdf';
      const docFile = path.resolve(demoDocumentsPath, docTermsPdf);
      const { basePath, accessToken, apiAccountId } = authResponse;
      const { clickwrapId } = await createClickwrap({ docFile, basePath, accessToken, accountId: apiAccountId });
      const res = await activateClickwrap({ clickwrapId, basePath, accessToken, accountId: apiAccountId });
          console.log({ res });
    }
 }
```

**docuSignService.js**

```
const SCOPES = ['signature', 'impersonation', 'openid', 'click.manage', 'click.send'];
const fs = require('fs');

const docusign = require('docusign-esign');

class DocusingService {
  async authenticate() {
    const jwtLifeSec = 10 * 60, // requested lifetime for the JWT is 10 min
      dsApi = new docusign.ApiClient();
    dsApi.setOAuthBasePath(process.env.dsOauthServer.replace('https://', '')); // it should be domain only.
    let rsaKey = fs.readFileSync(process.env.privateKeyLocation);
    try {
      const results = await dsApi.requestJWTUserToken(
        process.env.dsJWTClientId,
        process.env.impersonatedUserGuid,
        SCOPES,
        rsaKey,
        jwtLifeSec
      );
      const accessToken = results.body.access_token;
      // get user info
      const userInfoResults = await dsApi.getUserInfo(accessToken);
      // use the default account
      let userInfo = userInfoResults.accounts.find((account) => account.isDefault === 'true');
      return {
        accessToken: results.body.access_token,
        apiAccountId: userInfo.accountId,
        basePath: `${userInfo.baseUri}/restapi`
      };
    } catch (e) {
      let body = e.response && e.response.body;
      // Determine the source of the error
      if (body) {
        // The user needs to grant consent
        if (body.error && body.error === 'consent_required') {
          if (this.getConsent()) {
            return this.authenticate();
          }
        } else {
          // Consent has been granted. Show status code for DocuSign API error
          this._debug_log(`\nAPI problem: Status code ${e.response.status}, message body:
            ${JSON.stringify(body, null, 4)}\n\n`);
        }
      }
    }
  }

  getConsent() {
    var urlScopes = SCOPES.join('+');
    // Construct consent URL
    var redirectUri = 'https://developers.docusign.com/platform/auth/consent';
    var consentUrl =
      `${process.env.dsOauthServer}/oauth/auth?response_type=code&` +
      `scope=${urlScopes}&client_id=${process.env.dsJWTClientId}&` +
      `redirect_uri=${redirectUri}`;
    throw new Error(`Open the following URL in your browser to grant consent to the application: ${consentUrl}`);
  }

  getArgs(apiAccountId, accessToken, basePath, signerEmail, signerName, id, agreementData, redirect_uri) {
    const envelopeArgs = {
      signerEmail: signerEmail,
      signerName: signerName,
      status: 'sent',
      signerClientId: id,
      dsReturnUrl: redirect_uri,
      agreement: agreementData
    };
    const args = {
      accessToken: accessToken,
      basePath: basePath,
      accountId: apiAccountId,
      envelopeArgs: envelopeArgs
    };
    return args;
  }
}

module.exports = new DocusingService();
```

**createClickWrap.js**

```
const createClickwrap = async ({ docFile, clickwrapName = 'clickwrapName', basePath, accessToken, accountId }) => {
      // Step 3. Construct the request Body
      // Create display settings model
      const displaySettings = docusignClick.DisplaySettings.constructFromObject({
        consentButtonText: 'I Agree',
        displayName: 'Terms of Service',
        downloadable: true,
        format: 'modal',
        hasAccept: true,
        mustRead: true,
        requireAccept: true,
        documentDisplay: 'document'
      });
    
      // Create document model
      // Read and encode file. Put encoded value to Document entity.
      // The reads could raise an exception if the file is not available!
      const documentPdfExample = fs.readFileSync(docFile);
      const encodedExampleDocument = Buffer.from(documentPdfExample).toString('base64');
      const document = docusignClick.Document.constructFromObject({
        documentBase64: encodedExampleDocument,
        documentName: 'Terms of Service',
        fileExtension: 'pdf',
        order: 0
      });
    
      // Create clickwrapRequest model
      const clickwrapRequest = docusignClick.ClickwrapRequest.constructFromObject({
        displaySettings,
        documents: [document],
        name: clickwrapName,
        requireReacceptance: true
      });
    
      // Step 4. Call the Click API
      const dsApiClient = new docusignClick.ApiClient();
      dsApiClient.setBasePath(basePath);
      dsApiClient.addDefaultHeader('Authorization', 'Bearer ' + accessToken);
      const accountApi = new docusignClick.AccountsApi(dsApiClient);
    
      // Create a clickwrap
      let result = null;
      try {
        result = await accountApi.createClickwrap(accountId, {
          clickwrapRequest
        });
      } catch (e) {
        debugger;
        console.log(e);
      }
      debugger;
      console.log(`Clickwrap was created. ClickwrapId ${result.clickwrapId}`);
      return result;
    };

module.exports = { createClickwrap };
```

Parameters look like this in the demo app and it works:

![Screenshot 2022-06-27 at 10 56 47](https://user-images.githubusercontent.com/1593758/175909147-1e78a8eb-05a5-4103-a3bf-dfa69cc6f703.png)

and these are the parameters in my app:

![scrrenshot](https://user-images.githubusercontent.com/1593758/175909223-4b266c41-1a41-47d9-82f7-41417cbb4944.png)

The first parameter accountId is the same. Why I am getting this issue in my app if function gets the same parameters?

```
"Error: Not Found
    at Request.callback (/Users/and/test/node_modules/docusign-click/node_modules/superagent/lib/node/index.js:696:15)
    at IncomingMessage.<anonymous> (/Users/and/test/node_modules/docusign-click/node_modules/superagent/lib/node/index.js:906:18)
    at IncomingMessage.emit (node:events:539:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
```

**Comment by karankaushik95** [comment]
Its not easily evident what could be going on here. The easiest way to debug this would be to capture [API Request Logs](https://support.docusign.com/en/guides/ndse-user-guide-api-request-logging) for the successful and the unsuccessful requests and comparing them. 

If you need assistance with this, you can open a case with [DocuSign Developer Support](https://developers.docusign.com/support/) and my team can help you investigate this.

**Comment by AndrejGajdos** [comment]
@karankaushik95 thanks. When I changed `basePath` `${userInfo.baseUri}/restapi` to `${userInfo.baseUri}/clickapi`, it works now.
