### ISSUE TITLE
esbuild-bundled script crashes with ENOENT

### ISSUE THREAD

**Issue by mdesousa** [docusign/docusign-esign-node-client#340]
hi, we ran into this error after upgrading to version 6.5.0 of `docusign-esign`
it happens at runtime on aws lambda after bunding with esbuild
seems related to the recent upgrade to `super-agent-proxy@3.0.0`. it has a dependency to `vm2`.
see details below, i also found [a similar issue from another package](https://github.com/puppeteer/puppeteer/issues/10352) that may help

```
{
    "errorType": "Error",
    "errorMessage": "ENOENT: no such file or directory, open '/var/task/bridge.js'",
    "code": "ENOENT",
    "errno": -2,
    "syscall": "open",
    "path": "/var/task/bridge.js",
    "stack": [
      "Error: ENOENT: no such file or directory, open '/var/task/bridge.js'",
      "    at Object.openSync (node:fs:603:3)",
      "    at Object.readFileSync (node:fs:471:35)",
      "    at node_modules/vm2/lib/vm.js (/var/task/index.js:117737:66)",
      "    at __require (/var/task/index.js:12:50)",
      "    at node_modules/vm2/lib/main.js (/var/task/index.js:119609:9)",
      "    at __require (/var/task/index.js:12:50)",
      "    at node_modules/vm2/index.js (/var/task/index.js:119637:23)",
      "    at __require (/var/task/index.js:12:50)",
      "    at node_modules/degenerator/dist/src/index.js (/var/task/index.js:119649:17)",
      "    at __require (/var/task/index.js:12:50)"
    ]
  }
  ```

**Comment by ByungjaeChung** [comment]
Thanks for submitting the issue. This issue is reported to engineering with the following Jira: DEVDOCS-12876

**Comment by InbarGazit** [comment]
Should be fixed now, can you confirm that?
